In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN, LSTM, Bidirectional

In [3]:
# 학습 데이터 생성
train_X = [[[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]]
train_X = np.array(train_X, dtype=np.float32)
print(train_X.shape)

(1, 4, 5)


In [4]:
rnn = SimpleRNN(3)
# rnn = SimpleRNN(3, return_sequences=False, return_state=False)와 동일.
hidden_state = rnn(train_X)

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))

hidden state : [[ 0.9673498  -0.9658986  -0.97102344]], shape: (1, 3)


In [5]:
rnn = SimpleRNN(3, return_sequences=True)
hidden_states = rnn(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))

hidden states : [[[-0.8658316   0.98203033 -0.9141406 ]
  [-0.5034862   0.6556884   0.8866216 ]
  [-0.989243    0.1398449   0.79290205]
  [-0.5450048  -0.7309047  -0.2810755 ]]], shape: (1, 4, 3)


In [6]:
rnn = SimpleRNN(3, return_sequences=True, return_state=True)
hidden_states, last_state = rnn(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))

hidden states : [[[ 0.24538548 -0.9026676   0.99990463]
  [ 0.9458388  -0.9747323   0.99625903]
  [ 0.95616865 -0.19835968  0.99381375]
  [-0.09029972 -0.87858987  0.47479013]]], shape: (1, 4, 3)
last hidden state : [[-0.09029972 -0.87858987  0.47479013]], shape: (1, 3)


In [7]:
rnn = SimpleRNN(3, return_sequences=False, return_state=True)
hidden_state, last_state = rnn(train_X)

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))

hidden state : [[ 0.9085563  0.8373232 -0.6428081]], shape: (1, 3)
last hidden state : [[ 0.9085563  0.8373232 -0.6428081]], shape: (1, 3)
